### ISSUE TITLE
DefaultSessionManager seqnum npe

### ISSUE THREAD

**Issue by queer** [mewna/catnip#119]
```
java.lang.NullPointerException
	at com.mewna.catnip.shard.session.DefaultSessionManager.seqnum(DefaultSessionManager.java:62)
	at com.mewna.catnip.shard.CatnipShard.lambda$handleHello$10(CatnipShard.java:439)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:885)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:844)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by natanbc** [comment]
Maybe add a null check [here](https://github.com/mewna/catnip/blob/bed1e062020192f164f9af13036d4b670228617a/src/main/java/com/mewna/catnip/shard/session/DefaultSessionManager.java#L60-L63) and default to 0?
