### ISSUE TITLE
Occasional NPE on shard reboots

### ISSUE THREAD

**Issue by queer** [mewna/catnip#172]
```
Jan 01, 2019 9:16:46 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
	at com.mewna.catnip.shard.CatnipShard.handleControlMessage(CatnipShard.java:235)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:261)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:239)
	at io.vertx.core.eventbus.impl.EventBusImpl$InboundDeliveryContext.next(EventBusImpl.java:565)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$5(EventBusImpl.java:524)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by queer** [comment]
Taking a peek at the code, it's happening here `msg.reply(state.socketOpen());` which means that state is `null` I guess?
