### ISSUE TITLE
Fetching auditlog entires results in Exception

### ISSUE THREAD

**Issue by DRSchlaubi** [mewna/catnip#231]
I tried fetching auditlogs using
```Java            catnip.rest().guild().getGuildAuditLog("507517900127469568").user("416902379598774273").fetch()
```
And that exception got thrown
```Feb 08, 2019 7:05:23 PM io.vertx.core.impl.ContextImpl
SCHWERWIEGEND: Unhandled exception
java.lang.ClassCastException: io.vertx.core.json.JsonArray cannot be cast to java.util.List
	at com.mewna.catnip.rest.requester.AbstractRequester.lambda$handleResponse$2(AbstractRequester.java:256)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.mewna.catnip.rest.requester.AbstractRequester.handleResponse(AbstractRequester.java:254)
	at com.mewna.catnip.rest.requester.AbstractRequester$1.lambda$onResponse$1(AbstractRequester.java:206)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by natanbc** [comment]
That was a 400 response from discord. As for the error, I blame @queer, the code to handle errors in REST responses was written by her

**Comment by DRSchlaubi** [comment]
Then there is still an issue with the request

**Comment by queer** [comment]
Fixed in f3b582c

**Comment by DRSchlaubi** [comment]
But this has only fixed the handling of api error responses. The reauest would still return Bad request

**Comment by queer** [comment]
Ah my bad, I misunderstood. @samophis this is your code, you would know here

**Comment by SamOphis** [comment]
bad request means somewhere i've fucked up the actual format of the request, and since you're fetching it means i've messed up query params possibly. i'll look for a fix rn
