### ISSUE TITLE
DefaultShardManager Vert.x ReplyException

### ISSUE THREAD

**Issue by ForYaSee** [mewna/catnip#238]
Noticed this randomly after the bot was running some days.

```
[14:38:16] [INFO ] [vert.x-eventloop-thread-3 - 35] com.mewna.catnip.shard.manager.DefaultShardManager » Connecting shard 0 (queue len 1)
[14:38:16] [INFO ] [vert.x-eventloop-thread-4 - 36] com.mewna.catnip.shard.CatnipShard » Shard 0/1: We closed the websocket with code 4004
[14:38:16] [WARN ] [vert.x-eventloop-thread-4 - 36] com.mewna.catnip.shard.CatnipShard » Shard 0/1: Socket closing!
[14:38:16] [WARN ] [vert.x-eventloop-thread-4 - 36] com.mewna.catnip.shard.manager.DefaultShardManager » Ignoring duplicate queue for shard 0
[14:38:46] [WARN ] [vert.x-eventloop-thread-3 - 35] com.mewna.catnip.shard.manager.DefaultShardManager » Failed connecting shard 0 entirely, re-queueing
[14:38:46] [WARN ] [vert.x-eventloop-thread-3 - 35] com.mewna.catnip.shard.manager.DefaultShardManager » Stacktrace:
io.vertx.core.eventbus.ReplyException: Timed out after waiting 30000(ms) for a reply. address: __vertx.reply.5052, repliedAddress: catnip:shard:0:control
        at io.vertx.core.eventbus.impl.HandlerRegistration.sendAsyncResultFailure(HandlerRegistration.java:146) ~[gateway.jar:?]
        at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$new$0(HandlerRegistration.java:78) ~[gateway.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:907) ~[gateway.jar:?]
        at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:866) ~[gateway.jar:?]
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[gateway.jar:?]
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[gateway.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[gateway.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[gateway.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[gateway.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[gateway.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[gateway.jar:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
[14:38:46] [INFO ] [vert.x-eventloop-thread-3 - 35] com.mewna.catnip.shard.manager.DefaultShardManager » Connecting shard 0 (queue len 1)
[14:38:46] [INFO ] [vert.x-eventloop-thread-4 - 36] com.mewna.catnip.shard.CatnipShard » Shard 0/1: We closed the websocket with code 4004
[14:38:46] [WARN ] [vert.x-eventloop-thread-4 - 36] com.mewna.catnip.shard.CatnipShard » Shard 0/1: Socket closing!
[14:38:46] [WARN ] [vert.x-eventloop-thread-4 - 36] com.mewna.catnip.shard.manager.DefaultShardManager » Ignoring duplicate queue for shard 0
```

**Comment by queer** [comment]
@gabixdev

**Comment by Patologios** [comment]
Are you using latest catnip with my op 9 patch?

**Comment by gabixdev** [comment]
Are you using latest catnip with op 9 patch?

**Comment by ForYaSee** [comment]
@DRSchlaubi do we use that?

**Comment by DRSchlaubi** [comment]
I updated from 0.12.3 to 0.13.3 yesterday so I assume that you were using 0.12.3 at that point the error occurred

**Comment by queer** [comment]
Please re-open this if it becomes an issue again
