### ISSUE TITLE
Heartbeat zombies don't correctly requeue

### ISSUE THREAD

**Issue by queer** [mewna/catnip#241]
```
[16:11:44.119] [ WARN] [ c.m.c.shard.CatnipShard] Shard 18/20: Heartbeat zombie, queueing reconnect! 

Note the ~30-second pause here

[16:12:16.591] [ERROR] [ c.m.c.shard.CatnipShard] Shard 18/20: Exception in Websocket 
[16:12:16.591] [ERROR] [ c.m.c.shard.CatnipShard] Stacktrace:  
java.io.IOException: Connection reset by peer
    at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
    at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
    at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
    at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
    at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
    at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1128)
    at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)
[16:12:16.592] [ WARN] [ c.m.c.shard.CatnipShard] Shard 18/20: Socket closing! 
[16:12:16.592] [ INFO] [c.m.c.s.m.DefaultShardMa] Shard 18 closed, re-queuing... 
[16:12:16.592] [ INFO] [c.m.c.s.m.DefaultShardMa] Connecting shard 18 (queue len 0) 
[16:12:16.593] [ INFO] [c.m.c.s.m.DefaultShardMa] Deployed shard 18(/20) 
[16:12:16.764] [ INFO] [ c.m.c.shard.CatnipShard] Session invalidated (OP 9), clearing shard data and reconnecting 
[16:12:16.836] [ INFO] [ c.m.c.shard.CatnipShard] Shard 18/20: We closed the websocket with code 1000 
[16:12:16.836] [ WARN] [ c.m.c.shard.CatnipShard] Shard 18/20: Socket closing! 
[16:12:16.837] [ INFO] [c.m.c.s.m.DefaultShardMa] Shard 18 closed, re-queuing... 
[16:12:16.837] [ INFO] [c.m.c.s.m.DefaultShardMa] Connecting shard 18 (queue len 0) 
[16:12:16.837] [ INFO] [c.m.c.s.m.DefaultShardMa] Deployed shard 18(/20) 
[16:12:19.982] [ INFO] [c.m.c.s.m.DefaultShardMa] Connected shard 18(/20) 

And login actually works now here
```

cc @gabixdev

**Comment by queer** [comment]
Possibly related to #238?

**Comment by queer** [comment]
Should be fixed at this point(?), haven't seen it happen again
