### ISSUE TITLE
WS client occasionally fails to close correctly

### ISSUE THREAD

**Issue by queer** [mewna/catnip#418]
See ex. https://discordapp.com/channels/486311607400529931/486311631081570326/660235622434209802
I'm not sure how to reproduce this right now :<
cc @KJP12

**Comment by queer** [comment]
Cannot reproduce after several days of testing; will reopen if it comes up again.

**Comment by queer** [comment]
Finally managed to reproduce this :tada:

**Comment by queer** [comment]
Debug logs:
```
[01:13:20.830] [c.mewna.catnip.shard.CatnipShardImpl] Shard 0/1: Heartbeat zombie, queueing reconnect! 
[01:13:47.917] [c.mewna.catnip.shard.CatnipShardImpl] Shard 0/1: Couldn't connect socket: 
[01:13:47.921] [c.mewna.catnip.shard.CatnipShardImpl] Stacktrace:  
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:345)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:376)
        at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1153)
        at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:821)
        at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
        at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
        at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
        at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
        at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:968)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:923)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:923)
[01:14:02.080] [c.mewna.catnip.shard.CatnipShardImpl] Canceled timer task inside of itself: true 
```

**Comment by queer** [comment]
Tentatively want to say this is just the kind of stupid bug we've made in vert.x before in `CatnipShardImpl#onError` where we try to reply to a message after it's already replied to, causing failure.

**Comment by KJP12** [comment]
There is instances of this primarily with long-lived bots, and seems primarily isolated to Java 11, possible to avoid by using Java 12 or Java 13.
Jetbrains Runtime (OpenJDK 11.0.5) and Ubuntu's provided JDK (OpenJDK 11.0.6) have this issue.

The cause appears to be of a broken SSL implementation that locks an object permanently due to a never-ending or very long loop.

The following is on Ubuntu Server 18.04.4's OpenJDK 11.0.6 (Running under Arch Linux for the sake of debugging)
![2020-03-08T05:12:12 381799818](https://user-images.githubusercontent.com/8528256/76157037-597f8600-60b8-11ea-93e6-ee13d7cc778f.png)
![2020-03-08T05:11:59 679087325](https://user-images.githubusercontent.com/8528256/76157038-5a181c80-60b8-11ea-99dc-aff1d17ed30e.png)

**Comment by queer** [comment]
@KJP12 This does reproduce on 13 for me but without the SSL issues.

**Comment by KJP12** [comment]
I have found a reproducible cause: Loss of internet (ie, your ISP deciding to die, disconnecting from WIFI/Ethernet)
