### ISSUE TITLE
Getting Global Application Commands JsonParser Exception

### ISSUE THREAD

**Issue by ModdyLP** [mewna/catnip#510]
Hello,

If I try to delete an application command by id. The query for getting all application commands in global scope causes an Json Parser Error. That causes a Nullpointer in the following code.

The Method for getting the global Application Commands does not follow the schema. 

Method: catnip.rest().interaction().globalApplicationCommandsRaw.subscribe()

Stacktrace
```
Caused by: com.grack.nanojson.JsonParserException: JSON did not contain the correct type, expected JsonObject. on line 1, char 1891
    at com.grack.nanojson.JsonTokener.createParseException(Unknown Source)
    at com.grack.nanojson.JsonParser.parse(Unknown Source)
    at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source)
    at com.mewna.catnip.rest.ResponsePayload.object(ResponsePayload.java:48)
    ... 9 common frames omitted
```

For any further debug logs or informations pls contact me.

Kind Regards

**Comment by queer** [comment]
This should be fixed in 332f7961.
