### ISSUE TITLE
Events stop arriving at observable() listeners when an unhandled exception occurs 

### ISSUE THREAD

**Issue by skidunion** [mewna/catnip#524]
Log - [ws_disconnect.txt](https://github.com/mewna/catnip/files/6056558/ws_disconnect.txt)

Discord may force the instance to reconnect ([source](https://discord.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-opcodes)). After the bot reconnects, no events arrive at my `observable()` listeners (`MESSAGE_CREATE`), however, the bot receives the WS messages. I'm not sure if it only happens with `MESSAGE_CREATE` as I don't have any other listeners.

---
I would also like to mention the 502 error code that happend at some point, after which the disconnect occurred. Log - [log.txt](https://github.com/mewna/catnip/files/6056579/log.txt)
The code is 
```
message.channel().blockingGet().isGuild()
```
---
Catnip version ~ v3 `332f796`
JVM version ~ `AdoptOpenJDK 15.0.2`
Catnip options:
```
CatnipOptions options = new CatnipOptions(config.getString("token"))
        .intents(Set.of(DIRECT_MESSAGES, GUILDS, GUILD_MEMBERS, GUILD_MESSAGES))
        .rxScheduler(Schedulers.from(Executors.newFixedThreadPool(4))).chunkMembers(true);
```

**Comment by queer** [comment]
Immediate question: Does this reproduce?

We handle OP 7 appropriately:
https://github.com/mewna/catnip/blob/8a3ffef8896e329a618ead55f13f0f43158b48a0/src/main/java/com/mewna/catnip/shard/CatnipShardImpl.java#L225
https://github.com/mewna/catnip/blob/8a3ffef8896e329a618ead55f13f0f43158b48a0/src/main/java/com/mewna/catnip/shard/CatnipShardImpl.java#L589-L597
so that is unlikely to be the problem.

Do you still receive [lifecycle events](https://github.com/mewna/catnip/blob/8a3ffef8896e329a618ead55f13f0f43158b48a0/src/main/java/com/mewna/catnip/shard/LifecycleEvent.java) for the relevant shard?

If these all appear normal, can you peek at the [dispatch manager's registered consumers](https://github.com/mewna/catnip/blob/8a3ffef8896e329a618ead55f13f0f43158b48a0/src/main/java/com/mewna/catnip/shard/event/DefaultDispatchManager.java#L51) and check to make sure that things are actually registered?

> I would also like to mention the 502 error code that happend at some point, after which the disconnect occurred.

The 502 shouldn't be relevant.

**Comment by skidunion** [comment]
> Does this reproduce?
Yes, it does. It happens randomly, so I would need some time to check those things.

**Comment by skidunion** [comment]
You're right, it's not because of the code 4000 disconnect - consumers are there after a reconnect. Will continue to look for the issue.

**Comment by skidunion** [comment]
[log.txt](https://github.com/mewna/catnip/files/6069029/log.txt)
Had this issue again now, but it looks like the bot never attempted to reconnect. Haven't received the `LifecycleEvent.WEBSOCKET_CLOSED` though

**Comment by queer** [comment]
Interesting :thinking:

Digging through what should happen, it looks like it's getting added into the shard manager's queue but the connect task isn't ever running. I guess there's a failure state in which the task is never schedule (see ex. https://github.com/mewna/catnip/blob/8a3ffef8896e329a618ead55f13f0f43158b48a0/src/main/java/com/mewna/catnip/shard/manager/DefaultShardManager.java#L274-L278 ), but I can't imagine what it is.

**Comment by skidunion** [comment]
Okay, it looks like I'm able to reproduce the issue consistently, and it's not related to reconnects/disconnects.
Take the following code, for example:
```java
CatnipOptions options = new CatnipOptions(config.getString("token"))
    .intents(Set.of(DIRECT_MESSAGES, GUILDS, GUILD_MEMBERS, GUILD_MESSAGES))
    .rxScheduler(Schedulers.from(Executors.newFixedThreadPool(4))).chunkMembers(true);

Catnip.catnipAsync(options).subscribe(catnip -> {
   catnip.observable(DiscordEvent.MESSAGE_CREATE).subscribe(message -> {
       Logger.trace("Received {}", message.content());
       message.respond(message.content().substring(0, 2000));
   });

   catnip.connect();
});
```
It will throw an exception if the message is shorter than 2000 characters. The exception's stack trace in question is:
```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.StringIndexOutOfBoundsException: begin 0, end 2000, length 29
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 2000, length 29
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
	at java.base/java.lang.String.substring(String.java:1903)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 2000, length 29

	at net.skidunion.bot.NovoBot.lambda$start$1(NovoBot.java:106)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 8 more
Exception in thread "pool-4-thread-3" io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.StringIndexOutOfBoundsException: begin 0, end 2000, length 29
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 2000, length 29
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3734)
	at java.base/java.lang.String.substring(String.java:1903)
	at net.skidunion.bot.NovoBot.lambda$start$1(NovoBot.java:106)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 8 more
```
For the first time the message was received the code did print out a trace log. However, after the aforementioned exception occurred, no messages arrived at the listener.

I think what's happening here is that Catnip doesn't handle unhandled exceptions properly.

**Comment by queer** [comment]
This is an rx thing. Rx expects your code to handle uncaught exceptions, and will terminate the observable stream if one is thrown.

**Comment by queer** [comment]
To clarify: there’s not much I can do about this on a library level. Rx pushes it onto you.
