### ISSUE TITLE
Get current user guilds?

### ISSUE THREAD

**Issue by TheChilliPL** [mewna/catnip#582]
I'm trying to fetch every guild the bot is in using this piece of Kotlin code
```kt
val guildP = catnip.rest().user().getCurrentUserGuilds().fetch()
```
but it gives me errors in console:
```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | com.mewna.catnip.rest.RestPayloadException
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.util.NotificationLite.acceptFull(NotificationLite.java:292)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableBlockingSubscribe.subscribe(ObservableBlockingSubscribe.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableBlockingSubscribe.subscribe(ObservableBlockingSubscribe.java:105)
	at io.reactivex.rxjava3.core.Observable.blockingSubscribe(Observable.java:5890)
	at com.mewna.catnip.util.pagination.BasePaginator.lambda$fetch$4(BasePaginator.java:179)
	at io.reactivex.rxjava3.core.Observable.compose(Observable.java:6790)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:176)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:169)
	at com.mewna.catnip.util.pagination.BasePaginator.fetchWhile(BasePaginator.java:163)
	at com.mewna.catnip.util.pagination.BasePaginator.forEach(BasePaginator.java:142)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:122)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt:24)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt)
Caused by: com.mewna.catnip.rest.RestPayloadException
	at com.mewna.catnip.rest.requester.AbstractRequester.handleResponse(AbstractRequester.java:395)
	at com.mewna.catnip.rest.requester.AbstractRequester.lambda$executeHttpRequest$2(AbstractRequester.java:227)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: REST error context
	at com.mewna.catnip.rest.requester.AbstractRequester.queue(AbstractRequester.java:102)
	at com.mewna.catnip.rest.handler.RestUser.getCurrentUserGuildsRaw(RestUser.java:158)
	at com.mewna.catnip.rest.handler.RestUser$1.fetchNext(RestUser.java:125)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:176)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:169)
	at com.mewna.catnip.util.pagination.BasePaginator.fetchWhile(BasePaginator.java:163)
	at com.mewna.catnip.util.pagination.BasePaginator.forEach(BasePaginator.java:142)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:122)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt:24)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt)
Exception in thread "main" io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | com.mewna.catnip.rest.RestPayloadException
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.util.NotificationLite.acceptFull(NotificationLite.java:292)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableBlockingSubscribe.subscribe(ObservableBlockingSubscribe.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableBlockingSubscribe.subscribe(ObservableBlockingSubscribe.java:105)
	at io.reactivex.rxjava3.core.Observable.blockingSubscribe(Observable.java:5890)
	at com.mewna.catnip.util.pagination.BasePaginator.lambda$fetch$4(BasePaginator.java:179)
	at io.reactivex.rxjava3.core.Observable.compose(Observable.java:6790)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:176)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:169)
	at com.mewna.catnip.util.pagination.BasePaginator.fetchWhile(BasePaginator.java:163)
	at com.mewna.catnip.util.pagination.BasePaginator.forEach(BasePaginator.java:142)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:122)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt:24)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt)
Caused by: com.mewna.catnip.rest.RestPayloadException
	at com.mewna.catnip.rest.requester.AbstractRequester.handleResponse(AbstractRequester.java:395)
	at com.mewna.catnip.rest.requester.AbstractRequester.lambda$executeHttpRequest$2(AbstractRequester.java:227)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1458)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.RuntimeException: REST error context
	at com.mewna.catnip.rest.requester.AbstractRequester.queue(AbstractRequester.java:102)
	at com.mewna.catnip.rest.handler.RestUser.getCurrentUserGuildsRaw(RestUser.java:158)
	at com.mewna.catnip.rest.handler.RestUser$1.fetchNext(RestUser.java:125)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:176)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:169)
	at com.mewna.catnip.util.pagination.BasePaginator.fetchWhile(BasePaginator.java:163)
	at com.mewna.catnip.util.pagination.BasePaginator.forEach(BasePaginator.java:142)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:122)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt:24)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.mewna.catnip.util.pagination.BasePaginator.lambda$fetch$4(BasePaginator.java:182)
	at io.reactivex.rxjava3.core.Observable.compose(Observable.java:6790)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:176)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:169)
	at com.mewna.catnip.util.pagination.BasePaginator.fetchWhile(BasePaginator.java:163)
	at com.mewna.catnip.util.pagination.BasePaginator.forEach(BasePaginator.java:142)
	at com.mewna.catnip.util.pagination.BasePaginator.fetch(BasePaginator.java:122)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt:24)
	at me.patrykanuszczyk.inposter.MainKt.main(main.kt)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make private java.lang.Void() accessible: module java.base does not "opens java.lang" to unnamed module @329dbdbf
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at com.mewna.catnip.util.VoidHelper.<clinit>(VoidHelper.java:54)
	... 9 more
```

**Comment by queer** [comment]
Please catch the surrounding RestPayloadException and log its contents. If you need all guilds, you should likely just be teasing them from cache instead of via REST

**Comment by queer** [comment]
Ah nvm I'm dumb, try with `efc15984d` please

**Comment by TheChilliPL** [comment]
> Please catch the surrounding RestPayloadException and log its contents. If you need all guilds, you should likely just be teasing them from cache instead of via REST

How to get them from cache (and ensure I got all of them)? I'm just starting with Catnip

**Comment by queer** [comment]
> How to get them from cache

`catnip.cache().guilds()` will give you a read-only map (guild id -> guild object) of guilds

**Comment by TheChilliPL** [comment]
Does Discord report all guilds when the bot connects?

**Comment by queer** [comment]
Yes

**Comment by TheChilliPL** [comment]
The old code doesn't work with `efc15984d` either, just tested

**Comment by TheChilliPL** [comment]
Also,
```kt
val guild = catnip.cache().guilds().first()
```
seems to throw java.util.NoSuchElementException despite being in a single server.
I'm doing that right after catnip.connect(), maybe that's the problem?

**Comment by queer** [comment]
> I'm doing that right after catnip.connect()

You have to wait for the READY event
