### ISSUE TITLE
ConcurrentHashMap in MemoryEntityCache may block

### ISSUE THREAD

**Issue by queer** [mewna/catnip#91]
I got 1 warning when starting ~35 shards of blocking for too long (2 seconds); not sure why since no stacktrace was attached.

**Comment by queer** [comment]
https://gist.github.com/queer/30c4dd4fc11d95dc23c12429b6090c40

**Comment by natanbc** [comment]
```
	at app//com.google.common.collect.ImmutableList.forEach(ImmutableList.java:407)
	at app//com.mewna.catnip.cache.MemoryEntityCache.bulkCacheMembers(MemoryEntityCache.java:376)
	at app//com.mewna.catnip.entity.impl.EntityBuilder.createGuild(EntityBuilder.java:860)
	at app//com.mewna.catnip.entity.impl.EntityBuilder.createGuild(EntityBuilder.java:841)
```
possibly a large guild with too many members, since this happens on a loop (`at app//com.google.common.collect.ImmutableList.forEach`)?

**Comment by queer** [comment]
I can believe that, since we only call it on `GUILD_CREATE`
